polar:
   greeting: Welcome KIDDO to the local book catalog!
server:
   port: 9001
   tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5
   shutdown: graceful 
spring:
  application:
    name: catalog-service
  config:
    import:
    - "optional:configserver"
  cloud:
    config:
      uri:
      - http://localhost:8888
      request-connect-timeout: 5000 #5s
      request-read-timeout: 5000
      fail-fast: true
      retry:
        max-attempts: 6
        multiplier: 1.1
        initial-interval: 1000
        max-interval: 2000
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/polardb_catalog
#    url: jdbc:postgresql://${POSTGRES_HOST}:5432/polardb_catalog
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 10
  lifecycle:
    timeout-per-shutdown-phase: 15s 
# - For flyway  sql:
#    init:
#      mode: always
management: 
  endpoints:
    web:
      exposure:
        include:
        - refresh
        