name: Commit Stage
on:
  push:
  schedule: # Every Sunday Evening
    - cron: '0 0 * * 1'
env: 
  REGISTRY: ghcr.io
  IMAGE_NAME: codingkiddo/catalog-service
  VERSION: latest
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-22.04
    permissions:
      actions: write
      contents: write
      security-events: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: maven
      - name: Code vulnerability scanning
        uses: anchore/scan-action@v3
        id: scan 
        with: 
            path: "${{ github.workspace }}"
            fail-build: false
            severity-cutoff: low
            acs-report-enable: true
      - name: Upload vulnerability report
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure() 
        with: 
            sarif_file: ${{ steps.scan.outputs.sarif }}
      - name: Build, unit tests and integration tests
        run: |
          mvn --batch-mode --update-snapshots verify
            
            